pipelines:
  - name: S_B
    steps:
      - name: S_B_Jen_2
        type: Jenkins
        configuration:
          inputSteps:
            - name: S_B_Jen_1
          jenkinsJobName: testPipeline
          integrations:
            - name: test_jenkins
      - name: S_B_Jen_1
        type: Jenkins
        configuration:
          jenkinsJobName: testPipeline
          integrations:
            - name: test_jenkins
