resources:
   - name: myAppRepo_001
     type: GitRepo
     configuration:
       gitProvider: raksha78_github            
       path: raksha78/bash-step 
pipelines:
     - name: test_try
       configuration:
          environmentVariables:
            readOnly:
              MY_MESSAGE: '"Hello World!"'
       steps:
           - name: step_1
             type: Bash
             configuration:
               inputResources:
                 - name: myAppRepo_001
             execution:
               onExecute:
                 - echo $MY_MESSAGE
