template: true   # required for local templates   
valuesFilePath: ./values.yml # required for local templates. DO NOT SPECIFY for system level templates
    
pipelines:
  - name: {{ .Values.Pipeline.name }}
    steps:
      - name:  {{ .Values.step1.name }}
        type: Bash
        execution:         
          onExecute:
            - echo "Queuing steps for execution under node tests "
      - name:  {{ .Values.step2.name }}
        type: Bash
        configuration:
          inputSteps:
            - name:  {{ .Values.step2.input }}
        execution:         
          onExecute:
            - echo "Queuing steps for execution under node tests "
