template: true   # required for local templates   
valuesFilePath: ./values.yml # required for local templates. DO NOT SPECIFY for system level templates
key1: ["hello"]
pipelines:
  - name: {{ .Values.Pipeline.name }}
    steps:
      - name: main
        type: Bash
        execution:
          onExecute:
            - echo "Queuing steps for execution under node tests "
      {{- range .Values.steps }}
      {{ if eq(ne .name "hello") true }}
      - name: {{ .name }}
        type: Bash
        configuration:
          inputSteps:
            - name: {{ .input }}
        execution:
          onExecute:
            - echo "Queuing steps for execution under node tests "
      {{- end }}
      {{- end }}
