
   
template: true   # required for local templates   
valuesFilePath: ./path.yml # required for local templates. DO NOT SPECIFY for system level templates
    
pipelines:
  - name: "yoo"
    steps:
      - name: core
        type: Bash
        execution:
          onExecute:
            - echo "Queuing steps for execution under node tests "
      {{- range .Values.test.children }}
      - name: {{ .name }}
        type: Bash
        configuration:
          inputSteps:
            - name: core
        execution:
          onExecute:
            - echo "Queuing steps for execution under node tests "
      {{- end }}
