template: true   # required for local templates   
valuesFilePath: ./values.yml # required for local templates. DO NOT SPECIFY for system level templates
key1: ["step2"]

pipelines:
  - name: "yoo"
    steps:
      {{- range .Values.steps }} 
      {{ if ne .name {{- range key1 }} }}
      - name: {{ .name }}
        type: Bash
        execution:
          onExecute:
            - echo "Queuing steps for execution under node tests "
      {{ end }}
      {{ end }}
