
   
template: true   # required for local templates   
valuesFilePath: ./path.yml # required for local templates. DO NOT SPECIFY for system level templates
    
pipelines:
  - name: "yoo"
    steps:
      - name: main
        type: Bash
        execution:
          onExecute:
            - echo "Queuing steps for execution under node tests "
      {{- range .Values.test }}
        {{ if eq .name "core" }}
         {{- range .children }}
          $input := .name
          {{ if eq .type "directory" }} 
             {{- range .children }} 
      - name: {{ .name }}
        type: Bash
        configuration:
          inputSteps:
            - name: $input
        execution:
          onExecute:
            - echo "Queuing steps for execution under node tests "
             {{ end }}
          {{ else }}
      - name: {{ .name }}
        type: Bash
        configuration:
          inputSteps:
            - name: $input
        execution:
          onExecute:
            - echo "Queuing steps for execution under node tests "
          {{ end }}
        {{ end }}
        {{ end }}
      {{- end }}
